name: Example Error and Warning Logging
on: [push]

jobs:
  log-errors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate logs with errors
        run: |
          echo "This is a normal log message."
          echo "::error ::This is an error message."
  
  log-warnings:
    runs-on: ubuntu-latest
    steps:
      - name: Generate logs with warnings
        run: |
          echo "This is a normal warning message."
          echo "::warning file=app.js,line=20,col=5::This is a warning message."
      - name: Summarize Warning Logs
        run: |
          echo '### Warning Summary' > $GITHUB_STEP_SUMMARY
          echo 'A warning was generated in `app.js` at line 20, column 5.' >> $GITHUB_STEP_SUMMARY

  log-notices:
    runs-on: ubuntu-latest
    steps:
      - name: Generate logs with notices
        run: |
          echo "This is a normal notice message."
          echo "::notice ::This is a notice message."
